version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run The Roller and Upload
          command: |
            chmod a+x .circleci/act.sh ./script.sh .circleci/ghr
            echo "Running..."; .circleci/act.sh & ./script.sh $PatchCode $Link $BRANCH $GitHubMail $GitHubName $FTPHost $FTPUser $FTPPass
