version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run The Roller
          command: |
            chmod a+x .circleci/act.sh ./script.sh .circleci/ghr
            echo "Running..."; .circleci/act.sh & ./script.sh $PatchCode $Link $Branch $GitHubMail $GitHubName $FTPHost $FTPUser $FTPPass
      - run:
          name: Upload the Package to AFH
          command: |
            cd ~/project/files/
            for file in $PatchCode-$BRANCH*; do wput $file ftp://"$FTPUser":"$FTPPass"@"$FTPHost"//$PatchCode-NoRepo/ ; done
      - run:
          name: Upload the Package to transfer.sh
          command: |
            cd ~/project/files/
            for file in $PatchCode-$BRANCH*; do curl --upload-file $file https://transfer.sh/ && echo '' ; done
      - run:
          name: GitHub Release
          command: ghr -u $GitHubName -t $GITHUB_TOKEN -b 'Releasing The Necessary File Package for PatchROM' -n 'Compressed Files for $PatchCode' $PatchCode ~/project/files/
